-- CreateEnum
CREATE TYPE "TYPEPRODUCT" AS ENUM ('ACTIVE', 'DISABLE');

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "status" "TYPEPRODUCT" NOT NULL DEFAULT 'ACTIVE',
ALTER COLUMN "type" DROP NOT NULL;
